### ISSUE TITLE
[enhancement] PHP version

### ISSUE THREAD

**Issue by ramon82** [jasonmoo/t.js#14]
Hey, amazing library! I really like tiny and useful scripts.

So I made a PHP version for t.js: https://github.com/ramon82/t.php

Thanks for the code!

**Comment by jasonmoo** [comment]
Thanks man.  If you want to submit a pr with your PHP version noted in the readme like the coffeescript version I'll merge it.

**Comment by ramon82** [comment]
Done! :)
